CREATE TABLE medication (
                            id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255)
);

CREATE TABLE disease (
                         id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255)
);

CREATE TABLE users (
                       id BIGINT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR(255),
                       email VARCHAR(255),
                       password VARCHAR(255),
                       user_type VARCHAR(50)
);

CREATE TABLE disease_medication (
                                    disease_id BIGINT,
                                    medication_id BIGINT,
                                    PRIMARY KEY (disease_id, medication_id),
                                    FOREIGN KEY (disease_id) REFERENCES disease(id),
                                    FOREIGN KEY (medication_id) REFERENCES medication(id)
);

CREATE TABLE user_disease (
                              user_id BIGINT,
                              disease_id BIGINT,
                              PRIMARY KEY (user_id, disease_id),
                              FOREIGN KEY (user_id) REFERENCES users(id),
                              FOREIGN KEY (disease_id) REFERENCES disease(id)
);
